---
name: "Destroy Bicep"

on: # yamllint disable-line rule:truthy
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

  #=============================================================#
  # The following Variables should be set on the workflow level #
  #============================================================ #
  workflow_dispatch:
    inputs:
      environmentName:
        description: "Name of the Environment"
        required: true
        default: "dev"
      locationName:
        description: "Name of the deployment Location"
        required: true
        default: "westus"
      keyVaultName:
        description: "Environment Key Vault Name"
        required: true
        default: "kv-symphony-environments"

jobs:
  Destroy:
    uses: ./.github/workflows/template.bicep.destroy.yml
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
      locationName: ${{ github.event.inputs.locationName }}
      keyVaultName: ${{ github.event.inputs.keyVaultName }}
      branchName: ${{ github.ref_name }}
    secrets:
      azureEnviromentCredentials: ${{ secrets.AZURE_CREDENTIALS }}
