---
name: "CI Bicep"

on: # yamllint disable-line rule:truthy
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

  #=============================================================#
  # The following Variables should be set on the workflow level #
  #============================================================ #
  workflow_dispatch:
    inputs:
      environmentName:
        description: "Name of the Environment"
        required: true
        default: "dev"
      locationName:
        description: "Name of the deployment Location"
        required: true
        default: "westus"
      keyVaultName:
        description: "Environment Key Vault Name"
        required: true
        default: "kv-symphony-environments"

jobs:
  Validate:
    uses: ./.github/workflows/template.bicep.validate.yml
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
      environmentDirectory: ${{ github.event.inputs.environmentName }}
      locationName: ${{ github.event.inputs.locationName }}
      keyVaultName: ${{ github.event.inputs.keyVaultName }}
      branchName: ${{ github.ref_name }}
    secrets:
      azureEnviromentCredentials: ${{ secrets.AZURE_CREDENTIALS }}
    permissions:
      actions: read
      contents: read
      security-events: write

  PreviewDeploy:
    needs: Validate
    uses: ./.github/workflows/template.bicep.previewdeploy.yml
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
      environmentDirectory: ${{ github.event.inputs.environmentName }}
      locationName: ${{ github.event.inputs.locationName }}
      keyVaultName: ${{ github.event.inputs.keyVaultName }}
      branchName: ${{ github.ref_name }}
    secrets:
      azureEnviromentCredentials: ${{ secrets.AZURE_CREDENTIALS }}

  Test:
    needs: PreviewDeploy
    uses: ./.github/workflows/template.bicep.test.yml
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
      locationName: ${{ github.event.inputs.locationName }}
      keyVaultName: ${{ github.event.inputs.keyVaultName }}
      branchName: ${{ github.ref_name }}
    secrets:
      azureEnviromentCredentials: ${{ secrets.AZURE_CREDENTIALS }}
