name: "CI Bicep"

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

  workflow_dispatch:
    inputs:
      environmentName:
        description: "Name of the Environment"
        required: true
        default: "dev"
      locationName:
        description: "Name of the deployment Location"
        required: true
        default: "westus"
      keyVaultName:
        description: "Environment Key Vault Name"
        required: true
        default: "kv-symphony-env"

jobs:
  Validate:
    uses: ./.github/workflows/template.bicep.validate.yml
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
      locationName: ${{ github.event.inputs.locationName }}
      keyVaultName: ${{ github.event.inputs.keyVaultName }}
      branch: ${{ github.ref_name }}
    secrets:
      azureEnviromentCredentials: ${{ secrets.AZURE_CREDENTIALS }}

  PreviewDeploy:
    needs: Validate
    uses: ./.github/workflows/template.bicep.previewdeploy.yml
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
      locationName: ${{ github.event.inputs.locationName }}
      keyVaultName: ${{ github.event.inputs.keyVaultName }}
      branch: ${{ github.ref_name }}
    secrets:
      azureEnviromentCredentials: ${{ secrets.AZURE_CREDENTIALS }}
