---
name: PR Cleanup Terraform

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - closed
    branches:
      - main

concurrency:
  group: pr-${{ github.event.pull_request.number }}

env:
  KEY_VAULT_NAME: "kv-symphony-environments" #GitLeaksIgnore
  TERRAFORM_VERSION: "1.6.2"

permissions:
  id-token: write
  contents: read

jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      keyVaultName: ${{ steps.setValues.outputs.keyVaultName }}
      terraformVersion: ${{ steps.setValues.outputs.terraformVersion }}
    steps:
      - name: Set Values
        id: setValues
        run: |
          # shellcheck source=/dev/null
          echo "keyVaultName=${{ env.KEY_VAULT_NAME }}" >> $GITHUB_OUTPUT
          echo "terraformVersion=$TERRAFORM_VERSION" >> $GITHUB_OUTPUT

  Cleanup:
    needs: [Setup]
    uses: ./.github/workflows/template.terraform.cleanup.yml
    with:
      pullRequestNumber: ${{ github.event.pull_request.number }}
      keyVaultName: ${{ needs.Setup.outputs.keyVaultName }}
      terraformVersion: ${{ needs.Setup.outputs.terraformVersion }}
      githubEnvironment: symphony
    secrets: inherit
